#!/usr/bin/env python

from __future__ import print_function
import argparse
from xml.etree import ElementTree as ET

parser = argparse.ArgumentParser(description="Creates a PrivateKeys file from files specified on the command line")
parser.add_argument("files", nargs="*", help="A list of files to insert into the PrivateKeys structure")
parser.add_argument("-o", "--output", required="true", help="The name of the PrivateKeys XML file to output")
args = parser.parse_args()

# the XML components needed to make a PrivateKeys node
privateKeysPrefix = '<PrivateKeys count="{0}">'.format(len(args.files))
privateKeysSuffix = '</PrivateKeys>'

# open the output file for writing and add the private keys
with open(args.output, "wb") as output:
    print(privateKeysPrefix, file=output)

    for fileName in args.files:
        with open(fileName, 'rb') as f:
            for line in f.readlines():
                print(line, end='', file=output)
        # private key files generated by createPrincipal.py don't end in a newline
        print("", file=output)	
    print(privateKeysSuffix, file=output)
