#
rm fileClient/cert
rm fileClient/evidence
rm fileClient/fileKeys
rm fileClient/privatekey
rm fileClient/symkey
rm fileClient/files/tempfile*.test
rm fileClient/files/tempfile*.test.out
rm fileServer/cert
rm fileServer/evidence
rm fileServer/fileKeys
rm fileServer/privatekey
rm fileServer/symkey
rm fileServer/files/temp*.test
rm fileClient.log
rm fileServer.log
rm authClient/cert
rm authClient/evidence
rm authClient/fileKeys
rm authClient/privatekey
rm authClient/symkey
rm authClient/files/tempfile*.test
rm authClient/files/tempfile*.test.out
rm authServer/cert
rm authServer/evidence
rm authServer/fileKeys
rm authServer/privatekey
rm authServer/symkey
rm authServer/files/temp*.test
rm authClient.log
rm authServer.log
rm authServer/signingCert
rm authServer/signingKey
rm authServer/signingKeyMetaData
rm bidClient/cert
rm bidClient/evidence
rm bidClient/fileKeys
rm bidClient/privatekey
rm bidClient/symkey
rm bidClient/files/tempfile*.test
rm bidClient/files/tempfile*.test.out
rm bidServer/cert
rm bidServer/evidence
rm bidServer/fileKeys
rm bidServer/privatekey
rm bidServer/symkey
rm bidServer/files/temp*.test
rm bidClient.log
rm bidServer.log
