--- /usr/src/linux-3.10.1-guest/arch/x86/kvm/Makefile	2013-08-29 10:32:57.994043058 -0700
+++ Makefile	2013-08-29 18:56:19.039254556 -0700
@@ -13,10 +13,10 @@
 kvm-$(CONFIG_KVM_ASYNC_PF)	+= $(addprefix ../../../virt/kvm/, async_pf.o)
 
 kvm-y			+= x86.o mmu.o emulate.o i8259.o irq.o lapic.o \
-			   i8254.o cpuid.o pmu.o
+			   i8254.o cpuid.o pmu.o vmdd.o
 kvm-intel-y		+= vmx.o
 kvm-amd-y		+= svm.o
 
 obj-$(CONFIG_KVM)	+= kvm.o
 obj-$(CONFIG_KVM_INTEL)	+= kvm-intel.o
-obj-$(CONFIG_KVM_AMD)	+= kvm-amd.o
+obj-$(CONFIG_KVM_AMD)	+= kvm-amd.o
\ No newline at end of file
