// Code generated by protoc-gen-go.
// source: linux_admin_rpc.proto
// DO NOT EDIT!

package tao

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type LinuxAdminRPCRequest struct {
	Data             []byte   `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Path             *string  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Args             []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *LinuxAdminRPCRequest) Reset()         { *m = LinuxAdminRPCRequest{} }
func (m *LinuxAdminRPCRequest) String() string { return proto.CompactTextString(m) }
func (*LinuxAdminRPCRequest) ProtoMessage()    {}

func (m *LinuxAdminRPCRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LinuxAdminRPCRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *LinuxAdminRPCRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type LinuxAdminRPCHostedProgramList struct {
	Name             []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	Pid              []int32  `protobuf:"varint,2,rep,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *LinuxAdminRPCHostedProgramList) Reset()         { *m = LinuxAdminRPCHostedProgramList{} }
func (m *LinuxAdminRPCHostedProgramList) String() string { return proto.CompactTextString(m) }
func (*LinuxAdminRPCHostedProgramList) ProtoMessage()    {}

func (m *LinuxAdminRPCHostedProgramList) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *LinuxAdminRPCHostedProgramList) GetPid() []int32 {
	if m != nil {
		return m.Pid
	}
	return nil
}

type LinuxAdminRPCResponse struct {
	Data             []byte `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LinuxAdminRPCResponse) Reset()         { *m = LinuxAdminRPCResponse{} }
func (m *LinuxAdminRPCResponse) String() string { return proto.CompactTextString(m) }
func (*LinuxAdminRPCResponse) ProtoMessage()    {}

func (m *LinuxAdminRPCResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
}
