// Code generated by protoc-gen-go.
// source: linux_admin_rpc.proto
// DO NOT EDIT!

package tao

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type LinuxAdminRPCRequest struct {
	Data             []byte   `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Path             *string  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Args             []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *LinuxAdminRPCRequest) Reset()         { *m = LinuxAdminRPCRequest{} }
func (m *LinuxAdminRPCRequest) String() string { return proto.CompactTextString(m) }
func (*LinuxAdminRPCRequest) ProtoMessage()    {}

func (m *LinuxAdminRPCRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LinuxAdminRPCRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *LinuxAdminRPCRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type LinuxAdminRPCHostedProgram struct {
	Subprin          []byte `protobuf:"bytes,1,req,name=subprin" json:"subprin,omitempty"`
	Pid              *int32 `protobuf:"varint,2,req,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LinuxAdminRPCHostedProgram) Reset()         { *m = LinuxAdminRPCHostedProgram{} }
func (m *LinuxAdminRPCHostedProgram) String() string { return proto.CompactTextString(m) }
func (*LinuxAdminRPCHostedProgram) ProtoMessage()    {}

func (m *LinuxAdminRPCHostedProgram) GetSubprin() []byte {
	if m != nil {
		return m.Subprin
	}
	return nil
}

func (m *LinuxAdminRPCHostedProgram) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

type LinuxAdminRPCResponse struct {
	Child            []*LinuxAdminRPCHostedProgram `protobuf:"bytes,1,rep,name=child" json:"child,omitempty"`
	Name             []byte                        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *LinuxAdminRPCResponse) Reset()         { *m = LinuxAdminRPCResponse{} }
func (m *LinuxAdminRPCResponse) String() string { return proto.CompactTextString(m) }
func (*LinuxAdminRPCResponse) ProtoMessage()    {}

func (m *LinuxAdminRPCResponse) GetChild() []*LinuxAdminRPCHostedProgram {
	if m != nil {
		return m.Child
	}
	return nil
}

func (m *LinuxAdminRPCResponse) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
}
