// Code generated by protoc-gen-go.
// source: linux_host_admin_rpc.proto
// DO NOT EDIT!

package tao

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type LinuxHostAdminRPCRequest struct {
	Subprin          []byte   `protobuf:"bytes,1,opt,name=subprin" json:"subprin,omitempty"`
	Path             *string  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Args             []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *LinuxHostAdminRPCRequest) Reset()         { *m = LinuxHostAdminRPCRequest{} }
func (m *LinuxHostAdminRPCRequest) String() string { return proto.CompactTextString(m) }
func (*LinuxHostAdminRPCRequest) ProtoMessage()    {}

func (m *LinuxHostAdminRPCRequest) GetSubprin() []byte {
	if m != nil {
		return m.Subprin
	}
	return nil
}

func (m *LinuxHostAdminRPCRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *LinuxHostAdminRPCRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type LinuxHostAdminRPCHostedProgram struct {
	Subprin          []byte `protobuf:"bytes,1,req,name=subprin" json:"subprin,omitempty"`
	Pid              *int32 `protobuf:"varint,2,req,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LinuxHostAdminRPCHostedProgram) Reset()         { *m = LinuxHostAdminRPCHostedProgram{} }
func (m *LinuxHostAdminRPCHostedProgram) String() string { return proto.CompactTextString(m) }
func (*LinuxHostAdminRPCHostedProgram) ProtoMessage()    {}

func (m *LinuxHostAdminRPCHostedProgram) GetSubprin() []byte {
	if m != nil {
		return m.Subprin
	}
	return nil
}

func (m *LinuxHostAdminRPCHostedProgram) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

type LinuxHostAdminRPCResponse struct {
	Child            []*LinuxHostAdminRPCHostedProgram `protobuf:"bytes,1,rep,name=child" json:"child,omitempty"`
	Prin             []byte                            `protobuf:"bytes,2,opt,name=prin" json:"prin,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *LinuxHostAdminRPCResponse) Reset()         { *m = LinuxHostAdminRPCResponse{} }
func (m *LinuxHostAdminRPCResponse) String() string { return proto.CompactTextString(m) }
func (*LinuxHostAdminRPCResponse) ProtoMessage()    {}

func (m *LinuxHostAdminRPCResponse) GetChild() []*LinuxHostAdminRPCHostedProgram {
	if m != nil {
		return m.Child
	}
	return nil
}

func (m *LinuxHostAdminRPCResponse) GetPrin() []byte {
	if m != nil {
		return m.Prin
	}
	return nil
}

func init() {
}
