#!/bin/bash
cat <<EOF
menuentry 'TBOOT w/Linux 3.7.5' {
   recordfail
   insmod part_msdos
   insmod ext2
   set root='(/dev/sda,msdos5)'
   search --no-floppy --fs-uuid --set=root 8adf4b3e-8479-4da2-ad48-c5ecdd870f30
   multiboot /tboot.gz /tboot.gz logging=vga,memory,serial
   module /vmlinuz-3.7.5 /vmlinuz-3.7.5 root=/dev/mapper/sysvg-root ro quiet splash $vt_handoff
   module /initrd.img-3.7.5 /initrd.img-3.7.5
   module /3rd_gen_i5_i7_SINIT_51.BIN
}
EOF
