// Code generated by protoc-gen-go.
// source: rollback.proto
// DO NOT EDIT!

package fileproxy

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RollbackMessageType int32

const (
	RollbackMessageType_SET_COUNTER         RollbackMessageType = 1
	RollbackMessageType_GET_COUNTER         RollbackMessageType = 2
	RollbackMessageType_SET_HASH            RollbackMessageType = 3
	RollbackMessageType_GET_HASHED_VERIFIER RollbackMessageType = 4
	RollbackMessageType_ERROR               RollbackMessageType = 5
)

var RollbackMessageType_name = map[int32]string{
	1: "SET_COUNTER",
	2: "GET_COUNTER",
	3: "SET_HASH",
	4: "GET_HASHED_VERIFIER",
	5: "ERROR",
}
var RollbackMessageType_value = map[string]int32{
	"SET_COUNTER":         1,
	"GET_COUNTER":         2,
	"SET_HASH":            3,
	"GET_HASHED_VERIFIER": 4,
	"ERROR":               5,
}

func (x RollbackMessageType) Enum() *RollbackMessageType {
	p := new(RollbackMessageType)
	*p = x
	return p
}
func (x RollbackMessageType) String() string {
	return proto.EnumName(RollbackMessageType_name, int32(x))
}
func (x *RollbackMessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RollbackMessageType_value, data, "RollbackMessageType")
	if err != nil {
		return err
	}
	*x = RollbackMessageType(value)
	return nil
}

// A RollbackMessage is a message sent like an RPC between fileproxy hosts and a
// rollback server. The data is sometimes simply data and is sometimes a
// serialized protobuf, depending on the message type.
type RollbackMessage struct {
	Type             *RollbackMessageType `protobuf:"varint,1,req,name=type,enum=fileproxy.RollbackMessageType" json:"type,omitempty"`
	Data             []byte               `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *RollbackMessage) Reset()         { *m = RollbackMessage{} }
func (m *RollbackMessage) String() string { return proto.CompactTextString(m) }
func (*RollbackMessage) ProtoMessage()    {}

func (m *RollbackMessage) GetType() RollbackMessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RollbackMessageType_SET_COUNTER
}

func (m *RollbackMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// A RollbackHash is a hash for a given item.
type RollbackHash struct {
	Item             *string `protobuf:"bytes,1,req,name=item" json:"item,omitempty"`
	Hash             []byte  `protobuf:"bytes,2,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RollbackHash) Reset()         { *m = RollbackHash{} }
func (m *RollbackHash) String() string { return proto.CompactTextString(m) }
func (*RollbackHash) ProtoMessage()    {}

func (m *RollbackHash) GetItem() string {
	if m != nil && m.Item != nil {
		return *m.Item
	}
	return ""
}

func (m *RollbackHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// A RollbackResponse is the value received from the rollback server in response
// to a RollbackMessage.
type RollbackResponse struct {
	Type             *RollbackMessageType `protobuf:"varint,1,req,name=type,enum=fileproxy.RollbackMessageType" json:"type,omitempty"`
	Data             []byte               `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *RollbackResponse) Reset()         { *m = RollbackResponse{} }
func (m *RollbackResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackResponse) ProtoMessage()    {}

func (m *RollbackResponse) GetType() RollbackMessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RollbackMessageType_SET_COUNTER
}

func (m *RollbackResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("fileproxy.RollbackMessageType", RollbackMessageType_name, RollbackMessageType_value)
}
