// Code generated by protoc-gen-go.
// source: taosupport.proto
// DO NOT EDIT!

/*
Package taosupport is a generated protocol buffer package.

It is generated from these files:
	taosupport.proto

It has these top-level messages:
	SimpleMessage
*/
package taosupport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MessageType int32

const (
	MessageType_REQUEST  MessageType = 1
	MessageType_RESPONSE MessageType = 2
)

var MessageType_name = map[int32]string{
	1: "REQUEST",
	2: "RESPONSE",
}
var MessageType_value = map[string]int32{
	"REQUEST":  1,
	"RESPONSE": 2,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SimpleMessage struct {
	MessageType      *int32   `protobuf:"varint,1,req,name=message_type" json:"message_type,omitempty"`
	RequestType      *string  `protobuf:"bytes,2,req,name=request_type" json:"request_type,omitempty"`
	Err              *string  `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
	Data             [][]byte `protobuf:"bytes,4,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SimpleMessage) Reset()                    { *m = SimpleMessage{} }
func (m *SimpleMessage) String() string            { return proto.CompactTextString(m) }
func (*SimpleMessage) ProtoMessage()               {}
func (*SimpleMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SimpleMessage) GetMessageType() int32 {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return 0
}

func (m *SimpleMessage) GetRequestType() string {
	if m != nil && m.RequestType != nil {
		return *m.RequestType
	}
	return ""
}

func (m *SimpleMessage) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *SimpleMessage) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleMessage)(nil), "taosupport.SimpleMessage")
	proto.RegisterEnum("taosupport.MessageType", MessageType_name, MessageType_value)
}

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x49, 0xcc, 0x2f,
	0x2e, 0x2d, 0x28, 0xc8, 0x2f, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0x85, 0x71, 0xf1, 0x06, 0x67, 0xe6, 0x16, 0xe4, 0xa4, 0xfa, 0xa6, 0x16, 0x17, 0x27, 0xa6,
	0xa7, 0x0a, 0x89, 0x70, 0xf1, 0xe4, 0x42, 0x98, 0xf1, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a,
	0x4c, 0x1a, 0xac, 0x20, 0xd1, 0xa2, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x88, 0x28, 0x13, 0x50,
	0x94, 0x53, 0x88, 0x9b, 0x8b, 0x39, 0xb5, 0xa8, 0x48, 0x82, 0x59, 0x81, 0x11, 0xc8, 0xe1, 0xe1,
	0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x51, 0x60, 0xd6, 0xe0, 0xd1, 0xd2, 0xe0, 0xe2, 0x86,
	0x9a, 0x18, 0x02, 0x54, 0x0f, 0x54, 0xc9, 0x1e, 0xe4, 0x1a, 0x18, 0xea, 0x1a, 0x1c, 0x22, 0xc0,
	0x08, 0x54, 0xc9, 0x11, 0xe4, 0x1a, 0x1c, 0xe0, 0xef, 0x17, 0xec, 0x2a, 0xc0, 0x04, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xcc, 0x28, 0x84, 0x46, 0xa0, 0x00, 0x00, 0x00,
}
