// Code generated by protoc-gen-go.
// source: fileproxymessages.proto
// DO NOT EDIT!

/*
Package fileproxy is a generated protocol buffer package.

It is generated from these files:
	fileproxymessages.proto

It has these top-level messages:
	Message
	FileOperation
	OperationResult
	ResourceMasterInfo
	ResourceInfo
	PrincipalInfo
*/
package fileproxy

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MessageType int32

const (
	MessageType_AUTH_CERT    MessageType = 1
	MessageType_NONCE_CHALL  MessageType = 2
	MessageType_SIGNED_NONCE MessageType = 3
	MessageType_OP_RES       MessageType = 4
	MessageType_CREATE       MessageType = 5
	MessageType_DELETE       MessageType = 6
	MessageType_READ         MessageType = 7
	MessageType_WRITE        MessageType = 8
	MessageType_FILE_NEXT    MessageType = 9
	MessageType_FILE_LAST    MessageType = 10
)

var MessageType_name = map[int32]string{
	1:  "AUTH_CERT",
	2:  "NONCE_CHALL",
	3:  "SIGNED_NONCE",
	4:  "OP_RES",
	5:  "CREATE",
	6:  "DELETE",
	7:  "READ",
	8:  "WRITE",
	9:  "FILE_NEXT",
	10: "FILE_LAST",
}
var MessageType_value = map[string]int32{
	"AUTH_CERT":    1,
	"NONCE_CHALL":  2,
	"SIGNED_NONCE": 3,
	"OP_RES":       4,
	"CREATE":       5,
	"DELETE":       6,
	"READ":         7,
	"WRITE":        8,
	"FILE_NEXT":    9,
	"FILE_LAST":    10,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

// A Message is a message sent like an RPC between fileproxy hosts. The
// data is sometimes simply data and is sometimes a serialized protobuf,
// depending on the message type.
type Message struct {
	Type             *MessageType `protobuf:"varint,1,req,name=type,enum=fileproxy.MessageType" json:"type,omitempty"`
	Data             []byte       `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetType() MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MessageType_AUTH_CERT
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FileOperation struct {
	// The subject is the public key (in certificate form) of the principal taking
	// the action.
	Subject []byte `protobuf:"bytes,1,req,name=subject" json:"subject,omitempty"`
	// The name is the name of the file. The action is already specified by the
	// message type in the containing protobuf.
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FileOperation) Reset()         { *m = FileOperation{} }
func (m *FileOperation) String() string { return proto.CompactTextString(m) }
func (*FileOperation) ProtoMessage()    {}

func (m *FileOperation) GetSubject() []byte {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *FileOperation) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

// An OperationResult is the final return value from a sequence of operations,
// like the authentication of a principal.
type OperationResult struct {
	Result           *bool  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OperationResult) Reset()         { *m = OperationResult{} }
func (m *OperationResult) String() string { return proto.CompactTextString(m) }
func (*OperationResult) ProtoMessage()    {}

func (m *OperationResult) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

type ResourceMasterInfo struct {
	PrinName          *string `protobuf:"bytes,1,opt,name=prin_name" json:"prin_name,omitempty"`
	BaseDirectoryName *string `protobuf:"bytes,2,opt,name=base_directory_name" json:"base_directory_name,omitempty"`
	NumFileInfos      *int32  `protobuf:"varint,3,req,name=num_file_infos" json:"num_file_infos,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *ResourceMasterInfo) Reset()         { *m = ResourceMasterInfo{} }
func (m *ResourceMasterInfo) String() string { return proto.CompactTextString(m) }
func (*ResourceMasterInfo) ProtoMessage()    {}

func (m *ResourceMasterInfo) GetPrinName() string {
	if m != nil && m.PrinName != nil {
		return *m.PrinName
	}
	return ""
}

func (m *ResourceMasterInfo) GetBaseDirectoryName() string {
	if m != nil && m.BaseDirectoryName != nil {
		return *m.BaseDirectoryName
	}
	return ""
}

func (m *ResourceMasterInfo) GetNumFileInfos() int32 {
	if m != nil && m.NumFileInfos != nil {
		return *m.NumFileInfos
	}
	return 0
}

type ResourceInfo struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Type             *int32  `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Status           *int32  `protobuf:"varint,3,req,name=status" json:"status,omitempty"`
	Location         *string `protobuf:"bytes,4,req,name=location" json:"location,omitempty"`
	Size             *int32  `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	Owner            *string `protobuf:"bytes,6,opt,name=owner" json:"owner,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResourceInfo) Reset()         { *m = ResourceInfo{} }
func (m *ResourceInfo) String() string { return proto.CompactTextString(m) }
func (*ResourceInfo) ProtoMessage()    {}

func (m *ResourceInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ResourceInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ResourceInfo) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ResourceInfo) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *ResourceInfo) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *ResourceInfo) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

type PrincipalInfo struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Cert             []byte  `protobuf:"bytes,2,req,name=cert" json:"cert,omitempty"`
	Status           *int32  `protobuf:"varint,3,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrincipalInfo) Reset()         { *m = PrincipalInfo{} }
func (m *PrincipalInfo) String() string { return proto.CompactTextString(m) }
func (*PrincipalInfo) ProtoMessage()    {}

func (m *PrincipalInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PrincipalInfo) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *PrincipalInfo) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func init() {
	proto.RegisterEnum("fileproxy.MessageType", MessageType_name, MessageType_value)
}
