// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package simpleexample_messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	SimpleMessage
	RsaPrivateKeyMessage
	EcPrivateKeyMessage
	PrivateKeyMessage
*/
package simpleexample_messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_REQUEST  MessageType = 1
	MessageType_RESPONSE MessageType = 2
)

var MessageType_name = map[int32]string{
	1: "REQUEST",
	2: "RESPONSE",
}
var MessageType_value = map[string]int32{
	"REQUEST":  1,
	"RESPONSE": 2,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SimpleMessage struct {
	MessageType      *int32   `protobuf:"varint,1,req,name=message_type" json:"message_type,omitempty"`
	RequestType      *string  `protobuf:"bytes,2,req,name=request_type" json:"request_type,omitempty"`
	Err              *string  `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
	Data             [][]byte `protobuf:"bytes,4,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SimpleMessage) Reset()                    { *m = SimpleMessage{} }
func (m *SimpleMessage) String() string            { return proto.CompactTextString(m) }
func (*SimpleMessage) ProtoMessage()               {}
func (*SimpleMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SimpleMessage) GetMessageType() int32 {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return 0
}

func (m *SimpleMessage) GetRequestType() string {
	if m != nil && m.RequestType != nil {
		return *m.RequestType
	}
	return ""
}

func (m *SimpleMessage) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *SimpleMessage) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RsaPrivateKeyMessage struct {
	M                []byte `protobuf:"bytes,1,opt,name=m" json:"m,omitempty"`
	E                []byte `protobuf:"bytes,2,opt,name=e" json:"e,omitempty"`
	D                []byte `protobuf:"bytes,3,opt,name=d" json:"d,omitempty"`
	P                []byte `protobuf:"bytes,4,opt,name=p" json:"p,omitempty"`
	Q                []byte `protobuf:"bytes,5,opt,name=q" json:"q,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RsaPrivateKeyMessage) Reset()                    { *m = RsaPrivateKeyMessage{} }
func (m *RsaPrivateKeyMessage) String() string            { return proto.CompactTextString(m) }
func (*RsaPrivateKeyMessage) ProtoMessage()               {}
func (*RsaPrivateKeyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RsaPrivateKeyMessage) GetM() []byte {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *RsaPrivateKeyMessage) GetE() []byte {
	if m != nil {
		return m.E
	}
	return nil
}

func (m *RsaPrivateKeyMessage) GetD() []byte {
	if m != nil {
		return m.D
	}
	return nil
}

func (m *RsaPrivateKeyMessage) GetP() []byte {
	if m != nil {
		return m.P
	}
	return nil
}

func (m *RsaPrivateKeyMessage) GetQ() []byte {
	if m != nil {
		return m.Q
	}
	return nil
}

// The cheap way
type EcPrivateKeyMessage struct {
	DerBlob          []byte `protobuf:"bytes,1,opt,name=der_blob" json:"der_blob,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EcPrivateKeyMessage) Reset()                    { *m = EcPrivateKeyMessage{} }
func (m *EcPrivateKeyMessage) String() string            { return proto.CompactTextString(m) }
func (*EcPrivateKeyMessage) ProtoMessage()               {}
func (*EcPrivateKeyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EcPrivateKeyMessage) GetDerBlob() []byte {
	if m != nil {
		return m.DerBlob
	}
	return nil
}

type PrivateKeyMessage struct {
	KeyType          *string               `protobuf:"bytes,1,req,name=key_type" json:"key_type,omitempty"`
	RsaKey           *RsaPrivateKeyMessage `protobuf:"bytes,2,opt,name=rsa_key" json:"rsa_key,omitempty"`
	EcKey            *EcPrivateKeyMessage  `protobuf:"bytes,3,opt,name=ec_key" json:"ec_key,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PrivateKeyMessage) Reset()                    { *m = PrivateKeyMessage{} }
func (m *PrivateKeyMessage) String() string            { return proto.CompactTextString(m) }
func (*PrivateKeyMessage) ProtoMessage()               {}
func (*PrivateKeyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PrivateKeyMessage) GetKeyType() string {
	if m != nil && m.KeyType != nil {
		return *m.KeyType
	}
	return ""
}

func (m *PrivateKeyMessage) GetRsaKey() *RsaPrivateKeyMessage {
	if m != nil {
		return m.RsaKey
	}
	return nil
}

func (m *PrivateKeyMessage) GetEcKey() *EcPrivateKeyMessage {
	if m != nil {
		return m.EcKey
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleMessage)(nil), "simpleexample_messages.SimpleMessage")
	proto.RegisterType((*RsaPrivateKeyMessage)(nil), "simpleexample_messages.RsaPrivateKeyMessage")
	proto.RegisterType((*EcPrivateKeyMessage)(nil), "simpleexample_messages.EcPrivateKeyMessage")
	proto.RegisterType((*PrivateKeyMessage)(nil), "simpleexample_messages.PrivateKeyMessage")
	proto.RegisterEnum("simpleexample_messages.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4f, 0x83, 0x30,
	0x14, 0xc6, 0x53, 0xd8, 0xdc, 0x78, 0xa0, 0xc1, 0xba, 0x98, 0x1e, 0x09, 0x17, 0x1b, 0x35, 0x1c,
	0xbc, 0x1a, 0x8f, 0x9c, 0xcc, 0x74, 0xc2, 0xf4, 0x4a, 0xba, 0xf1, 0x62, 0x96, 0x8d, 0xc0, 0x5a,
	0x34, 0xf6, 0xcf, 0xf1, 0x3f, 0x35, 0x2d, 0x10, 0x0f, 0xe2, 0xa9, 0xbf, 0x7c, 0x5f, 0xbf, 0x2f,
	0xef, 0x3d, 0x38, 0xab, 0x50, 0x29, 0xf1, 0x8e, 0x2a, 0x69, 0x64, 0xdd, 0xd6, 0xf4, 0x52, 0xed,
	0xaa, 0xe6, 0x80, 0xf8, 0x25, 0xcc, 0x53, 0x0c, 0x6e, 0xfc, 0x06, 0xa7, 0xb9, 0x75, 0x96, 0x9d,
	0x42, 0x17, 0x10, 0xf4, 0x66, 0xd1, 0xea, 0x06, 0x19, 0x89, 0x1c, 0x3e, 0x35, 0xaa, 0xc4, 0xe3,
	0x07, 0xaa, 0xb6, 0x53, 0x9d, 0xc8, 0xe1, 0x1e, 0xf5, 0xc1, 0x45, 0x29, 0x99, 0x1b, 0x11, 0xee,
	0xd1, 0x00, 0x26, 0xa5, 0x68, 0x05, 0x9b, 0x44, 0x2e, 0x0f, 0xe2, 0x25, 0x2c, 0x32, 0x25, 0x56,
	0x72, 0xf7, 0x29, 0x5a, 0x7c, 0x44, 0x3d, 0xd4, 0x7b, 0x40, 0x2a, 0x46, 0x22, 0xc2, 0x03, 0x83,
	0xa6, 0xa8, 0xc7, 0xd2, 0xd6, 0x58, 0x6c, 0xd8, 0x64, 0xc0, 0x23, 0x9b, 0x1a, 0x8c, 0xaf, 0xe0,
	0x22, 0xdd, 0xfe, 0x6d, 0x0b, 0x61, 0x5e, 0xa2, 0x2c, 0x36, 0x87, 0x7a, 0xd3, 0x95, 0xc6, 0xdf,
	0x04, 0xce, 0x47, 0xff, 0xed, 0x51, 0xff, 0x2e, 0xe4, 0xd1, 0x07, 0x98, 0x49, 0x25, 0x8a, 0x3d,
	0x6a, 0x3b, 0x82, 0x7f, 0x77, 0x9b, 0x8c, 0x5f, 0x28, 0x19, 0x5d, 0xe3, 0x1e, 0x4e, 0x70, 0x6b,
	0xd3, 0xae, 0x4d, 0xdf, 0xfc, 0x97, 0x1e, 0x99, 0xfa, 0x9a, 0x83, 0xdf, 0xe3, 0x5a, 0x37, 0x48,
	0x7d, 0x98, 0x65, 0xe9, 0xcb, 0x6b, 0x9a, 0xaf, 0x43, 0x42, 0x03, 0x98, 0x67, 0x69, 0xbe, 0x7a,
	0x7e, 0xca, 0xd3, 0xd0, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x71, 0xb5, 0xa8, 0xc6, 0x01,
	0x00, 0x00,
}
