// Code generated by protoc-gen-go.
// source: resources.proto
// DO NOT EDIT!

/*
Package resourcemanager is a generated protocol buffer package.

It is generated from these files:
	resources.proto

It has these top-level messages:
	PrincipalInfo
	CombinedPrincipal
	ResourceInfo
	ResourceMasterInfo
*/
package resourcemanager

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResourceType int32

const (
	ResourceType_FILE      ResourceType = 1
	ResourceType_DIRECTORY ResourceType = 2
)

var ResourceType_name = map[int32]string{
	1: "FILE",
	2: "DIRECTORY",
}
var ResourceType_value = map[string]int32{
	"FILE":      1,
	"DIRECTORY": 2,
}

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}
func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}
func (x *ResourceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResourceType_value, data, "ResourceType")
	if err != nil {
		return err
	}
	*x = ResourceType(value)
	return nil
}
func (ResourceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PrincipalInfo struct {
	// Principal name (should match common name in cert, if user, OU if application).
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Signed certificate.
	Cert             []byte `protobuf:"bytes,2,opt,name=cert" json:"cert,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PrincipalInfo) Reset()                    { *m = PrincipalInfo{} }
func (m *PrincipalInfo) String() string            { return proto.CompactTextString(m) }
func (*PrincipalInfo) ProtoMessage()               {}
func (*PrincipalInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PrincipalInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PrincipalInfo) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

// A combined principal is several principals like application, user, all of
// which have to be authenticated to constitute an authorization.
type CombinedPrincipal struct {
	Principals       []*PrincipalInfo `protobuf:"bytes,1,rep,name=principals" json:"principals,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *CombinedPrincipal) Reset()                    { *m = CombinedPrincipal{} }
func (m *CombinedPrincipal) String() string            { return proto.CompactTextString(m) }
func (*CombinedPrincipal) ProtoMessage()               {}
func (*CombinedPrincipal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CombinedPrincipal) GetPrincipals() []*PrincipalInfo {
	if m != nil {
		return m.Principals
	}
	return nil
}

// Readers and writers can delegate writes.
// Writers to a directory can create and delete files in the directory.
type ResourceInfo struct {
	// Resource name,  e.g. - directory1/directory2/filename.
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// Always ResourceType.FILE.
	Type *int32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	// Encoded created time.
	DateCreated *string `protobuf:"bytes,3,opt,name=date_created,json=dateCreated" json:"date_created,omitempty"`
	// Encoded modified time.
	DateModified *string `protobuf:"bytes,4,opt,name=date_modified,json=dateModified" json:"date_modified,omitempty"`
	// Size in bytes.
	Size *int32 `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	// File encryption and integrity keys.
	Keys []byte `protobuf:"bytes,6,opt,name=keys" json:"keys,omitempty"`
	// List of owners.
	Owners []*CombinedPrincipal `protobuf:"bytes,7,rep,name=owners" json:"owners,omitempty"`
	// List of writers.
	Writers []*CombinedPrincipal `protobuf:"bytes,8,rep,name=writers" json:"writers,omitempty"`
	// List of readers.
	Readers          []*CombinedPrincipal `protobuf:"bytes,9,rep,name=readers" json:"readers,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ResourceInfo) Reset()                    { *m = ResourceInfo{} }
func (m *ResourceInfo) String() string            { return proto.CompactTextString(m) }
func (*ResourceInfo) ProtoMessage()               {}
func (*ResourceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResourceInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ResourceInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ResourceInfo) GetDateCreated() string {
	if m != nil && m.DateCreated != nil {
		return *m.DateCreated
	}
	return ""
}

func (m *ResourceInfo) GetDateModified() string {
	if m != nil && m.DateModified != nil {
		return *m.DateModified
	}
	return ""
}

func (m *ResourceInfo) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *ResourceInfo) GetKeys() []byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *ResourceInfo) GetOwners() []*CombinedPrincipal {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *ResourceInfo) GetWriters() []*CombinedPrincipal {
	if m != nil {
		return m.Writers
	}
	return nil
}

func (m *ResourceInfo) GetReaders() []*CombinedPrincipal {
	if m != nil {
		return m.Readers
	}
	return nil
}

type ResourceMasterInfo struct {
	// Service name owning resources (files).
	ServiceName *string `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	// Directory files are stored.
	BaseDirectoryName *string `protobuf:"bytes,2,opt,name=base_directory_name,json=baseDirectoryName" json:"base_directory_name,omitempty"`
	// Policy key used to sign user certs, etc.
	PolicyCert []byte `protobuf:"bytes,3,opt,name=policy_cert,json=policyCert" json:"policy_cert,omitempty"`
	// Resources.
	Resources        []*ResourceInfo `protobuf:"bytes,4,rep,name=resources" json:"resources,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ResourceMasterInfo) Reset()                    { *m = ResourceMasterInfo{} }
func (m *ResourceMasterInfo) String() string            { return proto.CompactTextString(m) }
func (*ResourceMasterInfo) ProtoMessage()               {}
func (*ResourceMasterInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResourceMasterInfo) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *ResourceMasterInfo) GetBaseDirectoryName() string {
	if m != nil && m.BaseDirectoryName != nil {
		return *m.BaseDirectoryName
	}
	return ""
}

func (m *ResourceMasterInfo) GetPolicyCert() []byte {
	if m != nil {
		return m.PolicyCert
	}
	return nil
}

func (m *ResourceMasterInfo) GetResources() []*ResourceInfo {
	if m != nil {
		return m.Resources
	}
	return nil
}

func init() {
	proto.RegisterType((*PrincipalInfo)(nil), "resourcemanager.PrincipalInfo")
	proto.RegisterType((*CombinedPrincipal)(nil), "resourcemanager.CombinedPrincipal")
	proto.RegisterType((*ResourceInfo)(nil), "resourcemanager.ResourceInfo")
	proto.RegisterType((*ResourceMasterInfo)(nil), "resourcemanager.ResourceMasterInfo")
	proto.RegisterEnum("resourcemanager.ResourceType", ResourceType_name, ResourceType_value)
}

func init() { proto.RegisterFile("resources.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0xaf, 0x93, 0x40,
	0x14, 0x0d, 0xf4, 0x93, 0x4b, 0x1b, 0xdb, 0x71, 0xc3, 0xc6, 0x2f, 0x5c, 0xd8, 0xb8, 0x60, 0xe1,
	0xc6, 0x44, 0x8d, 0x1b, 0x5a, 0x93, 0x26, 0x56, 0xcd, 0xd8, 0x8d, 0x2b, 0x42, 0xe1, 0xd6, 0x4c,
	0x2c, 0x0c, 0x99, 0x41, 0x1b, 0xfc, 0x7f, 0xef, 0x6f, 0xbc, 0xdf, 0xf2, 0x66, 0x06, 0x68, 0x79,
	0xed, 0xa6, 0x2b, 0x2e, 0x67, 0xce, 0xb9, 0x73, 0xcf, 0x99, 0x0b, 0x4f, 0x04, 0x4a, 0xfe, 0x57,
	0x24, 0x28, 0x83, 0x42, 0xf0, 0x92, 0x93, 0x13, 0x90, 0xc5, 0x79, 0xfc, 0x1b, 0x85, 0xff, 0x1e,
	0xa6, 0x3f, 0x04, 0xcb, 0x13, 0x56, 0xc4, 0x87, 0x75, 0xbe, 0xe7, 0x84, 0x40, 0x3f, 0x8f, 0x33,
	0xf4, 0xac, 0x97, 0xd6, 0xc2, 0xa1, 0xa6, 0xd6, 0x58, 0x82, 0xa2, 0xf4, 0x6c, 0x85, 0x4d, 0xa8,
	0xa9, 0xfd, 0x9f, 0x30, 0x0f, 0x79, 0xb6, 0x63, 0x39, 0xa6, 0xa7, 0x06, 0xe4, 0x33, 0x40, 0xd1,
	0xfe, 0x48, 0xd5, 0xa2, 0xb7, 0x70, 0xdf, 0x3d, 0x0f, 0x2e, 0xee, 0x0c, 0x1e, 0x5d, 0x48, 0x3b,
	0x0a, 0xff, 0xde, 0x86, 0x09, 0x6d, 0xd8, 0x17, 0xd3, 0xd8, 0xdd, 0x69, 0xca, 0xaa, 0x40, 0x33,
	0xcd, 0x80, 0x9a, 0x9a, 0xbc, 0x82, 0x49, 0x1a, 0x97, 0x18, 0x25, 0x02, 0xd5, 0x27, 0xf5, 0x7a,
	0x66, 0x7a, 0x57, 0x63, 0x61, 0x0d, 0x91, 0xd7, 0x30, 0x35, 0x94, 0x8c, 0xa7, 0x6c, 0xcf, 0x14,
	0xa7, 0x6f, 0x38, 0x46, 0xb7, 0x69, 0x30, 0xdd, 0x5b, 0xb2, 0xff, 0xe8, 0x0d, 0xea, 0xde, 0xba,
	0xd6, 0xd8, 0x1f, 0xac, 0xa4, 0x37, 0xac, 0xdd, 0xeb, 0x9a, 0x7c, 0x80, 0x21, 0x3f, 0xe6, 0x28,
	0xa4, 0x37, 0x32, 0x26, 0xfd, 0x2b, 0x93, 0x57, 0xe1, 0xd0, 0x46, 0x41, 0x3e, 0xc1, 0xe8, 0x28,
	0x58, 0xa9, 0xc5, 0xe3, 0x9b, 0xc5, 0xad, 0x44, 0xab, 0x95, 0xa1, 0x54, 0xab, 0x9d, 0xdb, 0xd5,
	0x8d, 0xc4, 0xbf, 0xb3, 0x80, 0xb4, 0x01, 0x6f, 0x62, 0xa9, 0x3a, 0x9a, 0x98, 0x55, 0x7c, 0x12,
	0xc5, 0x3f, 0x96, 0x60, 0xd4, 0x79, 0x7c, 0xb7, 0xc1, 0xbe, 0xe9, 0xd4, 0x03, 0x78, 0xba, 0x8b,
	0x25, 0x46, 0x29, 0x13, 0x98, 0x94, 0x5c, 0x54, 0x35, 0xd3, 0x36, 0xcc, 0xb9, 0x3e, 0x5a, 0xb6,
	0x27, 0x86, 0xff, 0x02, 0xdc, 0x82, 0x1f, 0x58, 0x52, 0x45, 0x66, 0x75, 0x7a, 0x26, 0x3c, 0xa8,
	0xa1, 0x50, 0x21, 0xe4, 0x23, 0x38, 0xa7, 0xed, 0x54, 0x6f, 0xa1, 0xad, 0x3c, 0xbb, 0xb2, 0xd2,
	0x5d, 0x06, 0x7a, 0xe6, 0xbf, 0x7d, 0x73, 0xde, 0x93, 0xad, 0x7e, 0xff, 0x31, 0xf4, 0xbf, 0xac,
	0xbf, 0xae, 0x66, 0x16, 0x99, 0x82, 0xb3, 0x5c, 0xd3, 0x55, 0xb8, 0xfd, 0x4e, 0x7f, 0xcd, 0xec,
	0x87, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x5e, 0x9e, 0x11, 0x02, 0x03, 0x00, 0x00,
}
