// Code generated by protoc-gen-go.
// source: protorpc.proto
// DO NOT EDIT!

/*
Package protorpc is a generated protocol buffer package.

It is generated from these files:
	protorpc.proto

It has these top-level messages:
	ProtoRPCRequestHeader
	ProtoRPCResponseHeader
*/
package protorpc

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// Protobuf RPC request header.
type ProtoRPCRequestHeader struct {
	// The service method.
	Op *string `protobuf:"bytes,1,req,name=op" json:"op,omitempty"`
	// The sequence number.
	Seq              *uint64 `protobuf:"varint,2,req,name=seq" json:"seq,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoRPCRequestHeader) Reset()         { *m = ProtoRPCRequestHeader{} }
func (m *ProtoRPCRequestHeader) String() string { return proto.CompactTextString(m) }
func (*ProtoRPCRequestHeader) ProtoMessage()    {}

func (m *ProtoRPCRequestHeader) GetOp() string {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return ""
}

func (m *ProtoRPCRequestHeader) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

// Protobuf RPC response header.
type ProtoRPCResponseHeader struct {
	// The service method (matches request op).
	Op *string `protobuf:"bytes,1,req,name=op" json:"op,omitempty"`
	// The sequence number (matches request seq).
	Seq *uint64 `protobuf:"varint,2,req,name=seq" json:"seq,omitempty"`
	// The optional error string.
	Error            *string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoRPCResponseHeader) Reset()         { *m = ProtoRPCResponseHeader{} }
func (m *ProtoRPCResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ProtoRPCResponseHeader) ProtoMessage()    {}

func (m *ProtoRPCResponseHeader) GetOp() string {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return ""
}

func (m *ProtoRPCResponseHeader) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *ProtoRPCResponseHeader) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func init() {
}
