// Code generated by protoc-gen-go.
// source: linux_host.proto
// DO NOT EDIT!

/*
Package tao is a generated protocol buffer package.

It is generated from these files:
	linux_host.proto

It has these top-level messages:
	LinuxHostSealedBundle
	LinuxHostConfig
*/
package tao

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LinuxHostSealedBundle struct {
	Policy           *string `protobuf:"bytes,1,req,name=policy" json:"policy,omitempty"`
	PolicyInfo       *string `protobuf:"bytes,2,opt,name=policy_info" json:"policy_info,omitempty"`
	Data             []byte  `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LinuxHostSealedBundle) Reset()                    { *m = LinuxHostSealedBundle{} }
func (m *LinuxHostSealedBundle) String() string            { return proto.CompactTextString(m) }
func (*LinuxHostSealedBundle) ProtoMessage()               {}
func (*LinuxHostSealedBundle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LinuxHostSealedBundle) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *LinuxHostSealedBundle) GetPolicyInfo() string {
	if m != nil && m.PolicyInfo != nil {
		return *m.PolicyInfo
	}
	return ""
}

func (m *LinuxHostSealedBundle) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LinuxHostConfig struct {
	// Either "root" or "stacked"
	Type *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	// Either "TPM", "TPM2", "pipe", "file", or "unix"
	ParentType *string `protobuf:"bytes,2,opt,name=parent_type" json:"parent_type,omitempty"`
	// For non-tpm parent types, the parent connection spec
	ParentSpec *string `protobuf:"bytes,3,opt,name=parent_spec" json:"parent_spec,omitempty"`
	// Socket directory, relative to host configuration directory.
	SocketDir *string `protobuf:"bytes,4,opt,name=socket_dir" json:"socket_dir,omitempty"`
	// Either "process", "docker", or "kvm_coreos"
	Hosting *string `protobuf:"bytes,5,req,name=hosting" json:"hosting,omitempty"`
	// Path to CoreOS image for hosted KVM, absolute or relative to domain.
	KvmCoreosImg *string `protobuf:"bytes,6,opt,name=kvm_coreos_img" json:"kvm_coreos_img,omitempty"`
	// KB of memory to allocate for each VM
	KvmCoreosVmMemory *int32 `protobuf:"varint,7,opt,name=kvm_coreos_vm_memory" json:"kvm_coreos_vm_memory,omitempty"`
	// Path to CoreOS authorized_keys for hosted KVM, absolute or relative to domain.
	KvmCoreosSshAuthKeys *string `protobuf:"bytes,8,opt,name=kvm_coreos_ssh_auth_keys" json:"kvm_coreos_ssh_auth_keys,omitempty"`
	// KB of memory to allocate for each VM with custom kernel and initram.
	KvmCustomVmMemory *int32 `protobuf:"varint,9,opt,name=kvm_custom_vm_memory" json:"kvm_custom_vm_memory,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (m *LinuxHostConfig) Reset()                    { *m = LinuxHostConfig{} }
func (m *LinuxHostConfig) String() string            { return proto.CompactTextString(m) }
func (*LinuxHostConfig) ProtoMessage()               {}
func (*LinuxHostConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LinuxHostConfig) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *LinuxHostConfig) GetParentType() string {
	if m != nil && m.ParentType != nil {
		return *m.ParentType
	}
	return ""
}

func (m *LinuxHostConfig) GetParentSpec() string {
	if m != nil && m.ParentSpec != nil {
		return *m.ParentSpec
	}
	return ""
}

func (m *LinuxHostConfig) GetSocketDir() string {
	if m != nil && m.SocketDir != nil {
		return *m.SocketDir
	}
	return ""
}

func (m *LinuxHostConfig) GetHosting() string {
	if m != nil && m.Hosting != nil {
		return *m.Hosting
	}
	return ""
}

func (m *LinuxHostConfig) GetKvmCoreosImg() string {
	if m != nil && m.KvmCoreosImg != nil {
		return *m.KvmCoreosImg
	}
	return ""
}

func (m *LinuxHostConfig) GetKvmCoreosVmMemory() int32 {
	if m != nil && m.KvmCoreosVmMemory != nil {
		return *m.KvmCoreosVmMemory
	}
	return 0
}

func (m *LinuxHostConfig) GetKvmCoreosSshAuthKeys() string {
	if m != nil && m.KvmCoreosSshAuthKeys != nil {
		return *m.KvmCoreosSshAuthKeys
	}
	return ""
}

func (m *LinuxHostConfig) GetKvmCustomVmMemory() int32 {
	if m != nil && m.KvmCustomVmMemory != nil {
		return *m.KvmCustomVmMemory
	}
	return 0
}

func init() {
	proto.RegisterType((*LinuxHostSealedBundle)(nil), "tao.LinuxHostSealedBundle")
	proto.RegisterType((*LinuxHostConfig)(nil), "tao.LinuxHostConfig")
}

func init() { proto.RegisterFile("linux_host.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8e, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0xfe, 0xd2, 0xa1, 0x6a, 0x91, 0xf9, 0x91, 0x17, 0x2c, 0xa2, 0xae, 0x58, 0x71,
	0x08, 0xd8, 0x20, 0xc4, 0x8e, 0x03, 0x58, 0x56, 0x32, 0x4d, 0xac, 0xc4, 0x9e, 0xc8, 0x9e, 0x20,
	0x72, 0x5f, 0x0e, 0x82, 0x9d, 0x48, 0x90, 0xee, 0xec, 0xef, 0xbd, 0xf7, 0x69, 0xe0, 0xa6, 0x35,
	0xae, 0xff, 0x56, 0x35, 0x05, 0x7e, 0xee, 0x3c, 0x31, 0x89, 0x25, 0x6b, 0x3a, 0xbd, 0xc3, 0xfd,
	0x47, 0x0a, 0xde, 0x22, 0xff, 0x44, 0xdd, 0x62, 0xf9, 0xd2, 0xbb, 0xb2, 0x45, 0x71, 0x80, 0x4d,
	0x47, 0xad, 0x29, 0x06, 0x99, 0xe5, 0x8b, 0xa7, 0x9d, 0xb8, 0x85, 0xeb, 0xe9, 0xaf, 0x8c, 0x3b,
	0x93, 0x5c, 0xe4, 0x59, 0x84, 0x7b, 0x58, 0x95, 0x9a, 0xb5, 0x5c, 0xc6, 0xca, 0xfe, 0xf4, 0x93,
	0xc1, 0xf1, 0x4f, 0xf6, 0x4a, 0xee, 0x6c, 0xaa, 0xd4, 0xe0, 0xa1, 0xc3, 0x99, 0x44, 0x7b, 0x74,
	0xac, 0x46, 0x38, 0x49, 0xfe, 0x61, 0xe8, 0xb0, 0x88, 0xae, 0x04, 0x05, 0x40, 0xa0, 0xa2, 0x41,
	0x56, 0xa5, 0xf1, 0x72, 0x35, 0xb2, 0x23, 0x6c, 0xd3, 0xf9, 0xc6, 0x55, 0x72, 0x3d, 0xea, 0x1e,
	0xe0, 0xd0, 0x7c, 0x59, 0x55, 0x90, 0x47, 0x0a, 0xca, 0xd8, 0x4a, 0x6e, 0xc6, 0xe2, 0x23, 0xdc,
	0xcd, 0x78, 0x7c, 0x59, 0xb4, 0xe4, 0x07, 0xb9, 0x8d, 0xe9, 0x5a, 0xe4, 0x20, 0x67, 0x69, 0x08,
	0xb5, 0xd2, 0x3d, 0xd7, 0xaa, 0xc1, 0x21, 0xc8, 0xab, 0x8b, 0x7d, 0x1f, 0x98, 0xec, 0x6c, 0xbf,
	0x4b, 0xfb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x25, 0x99, 0x2c, 0x4a, 0x01, 0x00, 0x00,
}
