// Code generated by protoc-gen-go.
// source: pipe_tao_channel_params.proto
// DO NOT EDIT!

package tao

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type PipeTaoChannelParams struct {
	Readfd           *int32 `protobuf:"varint,1,req,name=readfd" json:"readfd,omitempty"`
	Writefd          *int32 `protobuf:"varint,2,req,name=writefd" json:"writefd,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PipeTaoChannelParams) Reset()         { *m = PipeTaoChannelParams{} }
func (m *PipeTaoChannelParams) String() string { return proto.CompactTextString(m) }
func (*PipeTaoChannelParams) ProtoMessage()    {}

func (m *PipeTaoChannelParams) GetReadfd() int32 {
	if m != nil && m.Readfd != nil {
		return *m.Readfd
	}
	return 0
}

func (m *PipeTaoChannelParams) GetWritefd() int32 {
	if m != nil && m.Writefd != nil {
		return *m.Writefd
	}
	return 0
}

func init() {
}
