// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package tao is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	RPCRequest
	RPCResponse
*/
package tao

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RPCRequest struct {
	Data             []byte  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Size             *int32  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Policy           *string `protobuf:"bytes,3,opt,name=policy" json:"policy,omitempty"`
	Time             *int64  `protobuf:"varint,4,opt,name=time" json:"time,omitempty"`
	Expiration       *int64  `protobuf:"varint,5,opt,name=expiration" json:"expiration,omitempty"`
	Issuer           []byte  `protobuf:"bytes,6,opt,name=issuer" json:"issuer,omitempty"`
	Label            *string `protobuf:"bytes,7,opt,name=label" json:"label,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RPCRequest) Reset()                    { *m = RPCRequest{} }
func (m *RPCRequest) String() string            { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()               {}
func (*RPCRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RPCRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RPCRequest) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *RPCRequest) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *RPCRequest) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *RPCRequest) GetExpiration() int64 {
	if m != nil && m.Expiration != nil {
		return *m.Expiration
	}
	return 0
}

func (m *RPCRequest) GetIssuer() []byte {
	if m != nil {
		return m.Issuer
	}
	return nil
}

func (m *RPCRequest) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

type RPCResponse struct {
	Data             []byte  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Policy           *string `protobuf:"bytes,2,opt,name=policy" json:"policy,omitempty"`
	Counter          *int64  `protobuf:"varint,3,opt,name=counter" json:"counter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RPCResponse) Reset()                    { *m = RPCResponse{} }
func (m *RPCResponse) String() string            { return proto.CompactTextString(m) }
func (*RPCResponse) ProtoMessage()               {}
func (*RPCResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RPCResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RPCResponse) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *RPCResponse) GetCounter() int64 {
	if m != nil && m.Counter != nil {
		return *m.Counter
	}
	return 0
}

func init() {
	proto.RegisterType((*RPCRequest)(nil), "tao.RPCRequest")
	proto.RegisterType((*RPCResponse)(nil), "tao.RPCResponse")
}

/*
var fileDescriptor0 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x8d, 0x3f, 0xce, 0xc2, 0x30,
	0x0c, 0x47, 0xd5, 0xa6, 0x7f, 0x54, 0x7f, 0xfd, 0x40, 0xca, 0xe4, 0x11, 0x75, 0x62, 0xe2, 0x04,
	0x6c, 0x5c, 0x00, 0xf5, 0x06, 0xa1, 0x78, 0x88, 0x54, 0xea, 0x90, 0xb8, 0x12, 0xe5, 0xf4, 0x24,
	0x59, 0x90, 0x18, 0x9f, 0xad, 0xdf, 0x7b, 0xd0, 0x79, 0x37, 0x9d, 0x9c, 0x67, 0x61, 0xad, 0xc4,
	0xf0, 0xb0, 0x01, 0x8c, 0xd7, 0xcb, 0x48, 0xcf, 0x95, 0x82, 0xe8, 0x1e, 0xaa, 0xbb, 0x11, 0x83,
	0xc5, 0xa1, 0x38, 0xf6, 0x89, 0x82, 0x7d, 0x13, 0x96, 0x91, 0x6a, 0xbd, 0x83, 0xc6, 0xf1, 0x6c,
	0xa7, 0x0d, 0x55, 0xe4, 0x2e, 0x7d, 0xc5, 0x3e, 0x08, 0xab, 0x48, 0x4a, 0x6b, 0x00, 0x7a, 0x39,
	0xeb, 0x8d, 0x58, 0x5e, 0xb0, 0xce, 0xb7, 0xb8, 0xb0, 0x21, 0xac, 0xe4, 0xb1, 0xc9, 0xbe, 0x7f,
	0xa8, 0x67, 0x73, 0xa3, 0x19, 0xdb, 0x24, 0x18, 0xce, 0xf0, 0x97, 0xd3, 0xc1, 0xf1, 0x12, 0xe8,
	0xa7, 0xfd, 0xad, 0x95, 0xb9, 0xb6, 0x87, 0x76, 0xe2, 0x75, 0x91, 0x28, 0x4b, 0x79, 0xf5, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x29, 0xef, 0xa3, 0x74, 0xc9, 0x00, 0x00, 0x00,
}
*/
