// Code generated by protoc-gen-go.
// source: sealed_data.proto
// DO NOT EDIT!

package tao

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SealedData struct {
	Hash             *string `protobuf:"bytes,1,req,name=hash" json:"hash,omitempty"`
	HashAlg          *string `protobuf:"bytes,2,req,name=hash_alg" json:"hash_alg,omitempty"`
	Data             []byte  `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SealedData) Reset()         { *m = SealedData{} }
func (m *SealedData) String() string { return proto.CompactTextString(m) }
func (*SealedData) ProtoMessage()    {}

func (m *SealedData) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *SealedData) GetHashAlg() string {
	if m != nil && m.HashAlg != nil {
		return *m.HashAlg
	}
	return ""
}

func (m *SealedData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
}
