// Code generated by protoc-gen-go.
// source: tpm_tao.proto
// DO NOT EDIT!

package tao

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type HybridSealedData struct {
	SealedKey        []byte `protobuf:"bytes,1,req" json:"SealedKey,omitempty"`
	EncryptedData    []byte `protobuf:"bytes,2,req" json:"EncryptedData,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HybridSealedData) Reset()         { *m = HybridSealedData{} }
func (m *HybridSealedData) String() string { return proto.CompactTextString(m) }
func (*HybridSealedData) ProtoMessage()    {}

func (m *HybridSealedData) GetSealedKey() []byte {
	if m != nil {
		return m.SealedKey
	}
	return nil
}

func (m *HybridSealedData) GetEncryptedData() []byte {
	if m != nil {
		return m.EncryptedData
	}
	return nil
}
